apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: khushal-apps  # Using shared namespace

resources:
  # - namespace.yaml  # Namespace managed in shared/base
  - serviceaccount.yaml
  - database-configmap.yaml
  - timeline-deployment.yaml
  - contributor-deployment.yaml
  - ui-deployment.yaml

commonLabels:
  app: swaminarayan-timeline
  managed-by: kustomize

images:
  - name: ghcr.io/khushal1198/swaminarayan-timeline-timeline
    newTag: latest
  - name: ghcr.io/khushal1198/swaminarayan-timeline-contributor
    newTag: latest
  - name: ghcr.io/khushal1198/swaminarayan-timeline-ui
    newTag: latest