apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: swaminarayan-timeline  # Using its own namespace

resources:
  - namespace.yaml  # Each app has its own namespace
  - serviceaccount.yaml
  - external-secrets.yaml
  - database-configmap.yaml
  - timeline-deployment.yaml
  - contributor-deployment.yaml
  - ui-deployment.yaml

commonLabels:
  app: swaminarayan-timeline
  managed-by: kustomize

images:
  - name: ghcr.io/khushal1198/swaminarayan-timeline-timeline
    newTag: latest
  - name: ghcr.io/khushal1198/swaminarayan-timeline-contributor
    newTag: latest
  - name: ghcr.io/khushal1198/swaminarayan-timeline-ui
    newTag: latest